create table DEPOSIT_DETAIL  (
    DEPOSIT_DETAIL_ID	NUMBER(22) not null,
    DEPOSIT_ID	NUMBER(22) not null,
    ITEM_ID	NUMBER(22) not null,
    ITEM_AMOUNT DECIMAL(9,2),
    CREATION_DATE	DATE,
    DISABLE_BY	VARCHAR2(20),
    DISABLE_DATE	DATE,
    LAST_UPDATED_BY	VARCHAR2(20),
    LAST_UPDATE_DATE	DATE,
    IS_DELETED VARCHAR2(1) not null,
    primary key (DEPOSIT_DETAIL_ID),
    CONSTRAINT DEPOSIT_DETAIL_FK FOREIGN KEY (DEPOSIT_ID) REFERENCES DEPOSIT(DEPOSIT_ID),
    CONSTRAINT Item_DepositDetail_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
)