create table INSTALLMENT_DETAIL  (
        INSTALLMENT_DETAIL_ID	NUMBER(22) not null,
        INSTALLMENT_ID	NUMBER(22) not null,
        ITEM_ID	NUMBER(22) not null,
        ITEM_AMOUNT DECIMAL(9,2),
        CREATION_DATE	DATE,
        DISABLE_BY	VARCHAR2(20),
        DISABLE_DATE	DATE,
        LAST_UPDATED_BY	VARCHAR2(20),
        LAST_UPDATE_DATE	DATE,
        IS_DELETED VARCHAR2(1) not null,
        primary key (INSTALLMENT_DETAIL_ID),
        CONSTRAINT INSTALLMENT_Detail_FK FOREIGN KEY (INSTALLMENT_ID) REFERENCES INSTALLMENT(INSTALLMENT_ID),
        CONSTRAINT Item_Detail_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
)