create table CASE_DOCUMENT  (
    CASE_DOCUMENT_ID	NUMBER(22) not null,
    CASE_ID	NUMBER not null,
    DOCUMENT_NAME	VARCHAR2(100) not null,
    DOCUMENT_URL	VARCHAR2(200),
    CREATION_DATE	DATE,
    DISABLE_BY	VARCHAR2(20),
    DISABLE_DATE	DATE,
    LAST_UPDATED_BY	VARCHAR2(20),
    LAST_UPDATE_DATE	DATE,
    IS_DELETED VARCHAR2(1),
    primary key (CASE_DOCUMENT_ID),
    CONSTRAINT CASE_DOCUMENT_CASE_FK FOREIGN KEY (CASE_ID) REFERENCES CASE(CASE_ID)
)