create table SECURITY_BOX  (
    SECURITY_ID	NUMBER(22) not null,
    SECURITY_DEPOSIT DECIMAL(9,2),
    BRANCH_NAME	VARCHAR2(100),
    "SIZE"	VARCHAR2(100),
    LOCKER_TYPE	VARCHAR2(100),
    primary key (SECURITY_ID)
)