create table BOOKING  (
    BOOKING_ID	NUMBER(22) not null,
    BRANCH VARCHAR2(100) not null,
    LOCATION VARCHAR2(50) not null,
    STATUS VARCHAR2(100),
    "SIZE" VARCHAR2(100),
    "TYPE" VARCHAR2(100),
    "NUMBER" NUMBER,
    DOCUMENT_NAME VARCHAR2(100),
    CASE_ID NUMBER(22),
    primary key (BOOKING_ID),
    CONSTRAINT Case_Booking_FK FOREIGN KEY (CASE_ID) REFERENCES CASE(CASE_ID)
)